openapi: 3.0.3
info:
  title: Azure API Management Gateway AI Schema API
  description: The AI gateway capabilities in Azure API Management provide specialized features for managing, securing, and observing AI backend APIs including Azure OpenAI, OpenAI-compatible LLMs, MCP servers, and A2A agent APIs. Includes token rate limiting, semantic caching, load balancing across AI backends, and content safety enforcement.
  version: '2024-05-01'
  contact:
    name: Microsoft Azure
    url: https://learn.microsoft.com/en-us/azure/api-management/genai-gateway-capabilities
servers:
- url: https://{service-name}.azure-api.net
tags:
- name: Schema
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/workspaces/{workspaceId}/schemas
  : get:
      summary: Microsoft Azure API Management WorkspaceGlobalSchema_ListByService
      operationId: WorkspaceGlobalSchema_ListByService
      description: Lists a collection of schemas registered with workspace in a service instance.
      responses:
        '200':
          description: Success
      tags:
      - Schema
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/workspaces/{workspaceId}/schemas/{schemaId}
  : head:
      summary: Microsoft Azure API Management WorkspaceGlobalSchema_GetEntityTag
      operationId: WorkspaceGlobalSchema_GetEntityTag
      description: Gets the entity state (Etag) version of the Schema specified by its identifier.
      responses:
        '200':
          description: Success
      tags:
      - Schema
    get:
      summary: Microsoft Azure API Management WorkspaceGlobalSchema_Get
      operationId: WorkspaceGlobalSchema_Get
      description: Gets the details of the Schema specified by its identifier.
      responses:
        '200':
          description: Success
      tags:
      - Schema
    put:
      summary: Microsoft Azure API Management WorkspaceGlobalSchema_CreateOrUpdate
      operationId: WorkspaceGlobalSchema_CreateOrUpdate
      description: Creates new or updates existing specified Schema of the workspace in an API Management service instance.
      responses:
        '200':
          description: Success
      tags:
      - Schema
    delete:
      summary: Microsoft Azure API Management WorkspaceGlobalSchema_Delete
      operationId: WorkspaceGlobalSchema_Delete
      description: Deletes specific Schema.
      responses:
        '200':
          description: Success
      tags:
      - Schema
externalDocs:
  description: Documentation
  url: https://learn.microsoft.com/en-us/azure/api-management/genai-gateway-capabilities
x-generated-from: documentation
