openapi: 3.0.3
info:
  title: Azure API Management Gateway AI GatewayApi API
  description: The AI gateway capabilities in Azure API Management provide specialized features for managing, securing, and observing AI backend APIs including Azure OpenAI, OpenAI-compatible LLMs, MCP servers, and A2A agent APIs. Includes token rate limiting, semantic caching, load balancing across AI backends, and content safety enforcement.
  version: '2024-05-01'
  contact:
    name: Microsoft Azure
    url: https://learn.microsoft.com/en-us/azure/api-management/genai-gateway-capabilities
servers:
- url: https://{service-name}.azure-api.net
tags:
- name: GatewayApi
paths:
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/gateways/{gatewayId}/apis
  : get:
      summary: Microsoft Azure API Management GatewayApi_ListByService
      operationId: GatewayApi_ListByService
      description: Lists a collection of the APIs associated with a gateway.
      responses:
        '200':
          description: Success
      tags:
      - GatewayApi
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/gateways/{gatewayId}/apis/{apiId}
  : head:
      summary: Microsoft Azure API Management GatewayApi_GetEntityTag
      operationId: GatewayApi_GetEntityTag
      description: Checks that API entity specified by identifier is associated with the Gateway entity.
      responses:
        '200':
          description: Success
      tags:
      - GatewayApi
    put:
      summary: Microsoft Azure API Management GatewayApi_CreateOrUpdate
      operationId: GatewayApi_CreateOrUpdate
      description: Adds an API to the specified Gateway.
      responses:
        '200':
          description: Success
      tags:
      - GatewayApi
    delete:
      summary: Microsoft Azure API Management GatewayApi_Delete
      operationId: GatewayApi_Delete
      description: Deletes the specified API from the specified Gateway.
      responses:
        '200':
          description: Success
      tags:
      - GatewayApi
externalDocs:
  description: Documentation
  url: https://learn.microsoft.com/en-us/azure/api-management/genai-gateway-capabilities
x-generated-from: documentation
